# ДЗ: NumPy и Pandas

In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [2]:
data = pd.read_csv("melb_data.csv")
data.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [3]:
data.shape

(13580, 21)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  object 
 1   Address        13580 non-null  object 
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  object 
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object 
 6   SellerG        13580 non-null  object 
 7   Date           13580 non-null  object 
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object 
 17  Lattitude      13580 non-null  float64
 18  Longti

In [5]:
data.describe()

Rooms         Price      Distance      Postcode      Bedroom2  \
count  13580.000000  1.358000e+04  13580.000000  13580.000000  13580.000000   
mean       2.937997  1.075684e+06     10.137776   3105.301915      2.914728   
std        0.955748  6.393107e+05      5.868725     90.676964      0.965921   
min        1.000000  8.500000e+04      0.000000   3000.000000      0.000000   
25%        2.000000  6.500000e+05      6.100000   3044.000000      2.000000   
50%        3.000000  9.030000e+05      9.200000   3084.000000      3.000000   
75%        3.000000  1.330000e+06     13.000000   3148.000000      3.000000   
max       10.000000  9.000000e+06     48.100000   3977.000000     20.000000   

           Bathroom           Car       Landsize  BuildingArea    YearBuilt  \
count  13580.000000  13518.000000   13580.000000   7130.000000  8205.000000   
mean       1.534242      1.610075     558.416127    151.967650  1964.684217   
std        0.691712      0.962634    3990.669241    541.014538    37.273762   
min        0.000000      0.000000       0.000000      0.000000  1196.000000   
25%        1.000000      1.000000     177.000000     93.000000  1940.000000   
50%        1.000000      2.000000     440.000000    126.000000  1970.000000   
75%        2.000000      2.000000     651.000000    174.000000  1999.000000   
max        8.000000     10.000000  433014.000000  44515.000000  2018.000000   

          Lattitude    Longtitude  Propertycount  
count  13580.000000  13580.000000   13580.000000  
mean     -37.809203    144.995216    7454.417378  
std        0.079260      0.103916    4378.581772  
min      -38.182550    144.431810     249.000000  
25%      -37.856822    144.929600    4380.000000  
50%      -37.802355    145.000100    6555.000000  
75%      -37.756400    145.058305   10331.000000  
max      -37.408530    145.526350   21650.000000

In [6]:
data.duplicated().sum()

0

In [7]:
data['Regionname'].unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria'], dtype=object)

In [8]:
data.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [9]:
len(data[data['YearBuilt'] < 1900])

368

In [10]:
data.corr()

Rooms     Price  Distance  Postcode  Bedroom2  Bathroom  \
Rooms          1.000000  0.496634  0.294203  0.055303  0.944190  0.592934   
Price          0.496634  1.000000 -0.162522  0.107867  0.475951  0.467038   
Distance       0.294203 -0.162522  1.000000  0.431514  0.295927  0.127155   
Postcode       0.055303  0.107867  0.431514  1.000000  0.060584  0.113664   
Bedroom2       0.944190  0.475951  0.295927  0.060584  1.000000  0.584685   
Bathroom       0.592934  0.467038  0.127155  0.113664  0.584685  1.000000   
Car            0.408483  0.238979  0.262994  0.050289  0.405325  0.322246   
Landsize       0.025678  0.037507  0.025004  0.024558  0.025646  0.037130   
BuildingArea   0.124127  0.090981  0.099481  0.055475  0.122319  0.111933   
YearBuilt     -0.065413 -0.323617  0.246379  0.032863 -0.053319  0.152702   
Lattitude      0.015948 -0.212934 -0.130723 -0.406104  0.015925 -0.070594   
Longtitude     0.100771  0.203656  0.239425  0.445357  0.102238  0.118971   
Propertycount -0.081530 -0.042153 -0.054910  0.062304 -0.081350 -0.052201   

                    Car  Landsize  BuildingArea  YearBuilt  Lattitude  \
Rooms          0.408483  0.025678      0.124127  -0.065413   0.015948   
Price          0.238979  0.037507      0.090981  -0.323617  -0.212934   
Distance       0.262994  0.025004      0.099481   0.246379  -0.130723   
Postcode       0.050289  0.024558      0.055475   0.032863  -0.406104   
Bedroom2       0.405325  0.025646      0.122319  -0.053319   0.015925   
Bathroom       0.322246  0.037130      0.111933   0.152702  -0.070594   
Car            1.000000  0.026770      0.096101   0.104515  -0.001963   
Landsize       0.026770  1.000000      0.500485   0.036451   0.009695   
BuildingArea   0.096101  0.500485      1.000000   0.019665   0.043420   
YearBuilt      0.104515  0.036451      0.019665   1.000000   0.060445   
Lattitude     -0.001963  0.009695      0.043420   0.060445   1.000000   
Longtitude     0.063395  0.010833     -0.023810  -0.003470  -0.357634   
Propertycount -0.024295 -0.006854     -0.028840   0.006361   0.047086   

               Longtitude  Propertycount  
Rooms            0.100771      -0.081530  
Price            0.203656      -0.042153  
Distance         0.239425      -0.054910  
Postcode         0.445357       0.062304  
Bedroom2         0.102238      -0.081350  
Bathroom         0.118971      -0.052201  
Car              0.063395      -0.024295  
Landsize         0.010833      -0.006854  
BuildingArea    -0.023810      -0.028840  
YearBuilt       -0.003470       0.006361  
Lattitude       -0.357634       0.047086  
Longtitude       1.000000       0.065988  
Propertycount    0.065988       1.000000

In [11]:
data.groupby(['Regionname'])['Price'].count()

Regionname
Eastern Metropolitan          1471
Eastern Victoria                53
Northern Metropolitan         3890
Northern Victoria               41
South-Eastern Metropolitan     450
Southern Metropolitan         4695
Western Metropolitan          2948
Western Victoria                32
Name: Price, dtype: int64

### Numpy

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [12]:
A = np.array([[1, -2, 4], [2, 0, -1]])
B = np.array([[5, 2, 3], [4, 6, 2]])
A+B, A-B

(array([[6, 0, 7],
        [6, 6, 1]]),
 array([[-4, -4,  1],
        [-2, -6, -3]]))

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [13]:
A = np.array([[1, 2], [2, -1], [3, 0]])
B = np.array([[-1, 1], [1, 2], [0, 0]])
C = A-3*B
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [14]:
A = np.array([[1, -1], [2, 0], [3, 0]])
B = np.array([[1, 1], [2, 0]])
C = A@B
C

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [15]:
A = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])
np.linalg.det(A)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [16]:
A = np.array([[3, 3, -1], [4, 1, 3], [1, -2, -2]])
Ainv = np.linalg.inv(A)
assert(np.allclose(A @ Ainv, np.eye(3)))
assert(np.allclose(Ainv @ A, np.eye(3)))
Ainv

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])